name: Build and deploy NestJS API

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Create Clean Zip
        run: zip -r deploy_ready.zip . -x "*.git*" "node_modules/*" ".pnpm-store/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy_ready.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06CA381582F54E3B97474EB74EC44CF5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E04241B78AC2477AA922A7C0A8662A10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D1A24211C19B4606B9EC4847A9D9C782 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'diupoint-api'
          package: deploy_ready.zip
